### PR TITLE
Add imageValidator factory

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Any idea how to test this bloody thing? I want to test that it returns `true` for an image URL and `false` for a non-image URL.

**Comment by stulees** [comment]
@donnapep I'm not sure how you could test this. I don't think it should deter from merging though. However, I still personally feel validating for acceptable file extension is sufficient ...

**Comment by donnapep** [comment]
@stulees OK, shall I merge this then? I leave it to your discretion whether or not you choose to use this functionality. Thx.

**Comment by stulees** [comment]
@donnapep Sounds fine :+1:

**Pull request merged**
